### ISSUE TITLE
tests failing due to project bind issues

### ISSUE THREAD

**Issue by paulushcgcj** [bcgov-nr/action-test-and-analyse-java#12]
It seems like this action tests are failing due to inconsistency in sonar configuration.

The project is complaining about biding with the following message

```
[INFO] Load project branches (done) | time=808ms
[INFO] Check ALM binding of project 'bcgov_bcgov-nr/action-test-and-analyse-java'
Warning:  Failed to check if project 'bcgov_bcgov-nr/action-test-and-analyse-java' is bound
[INFO] Detected project binding: ERROR
[INFO] Check ALM binding of project 'bcgov_bcgov-nr/action-test-and-analyse-java' (done) | time=825ms
```

**Comment by paulushcgcj** [comment]
https://github.com/bcgov-nr/action-test-and-analyse-java/actions/runs/5427247946/jobs/9871736052#step:3:11497

**Comment by DerekRoberts** [comment]
Solved!  I weaseled code weaseled into Paulo's PR #10.
